//Creating an array of colours
let buttonColours = ["red", "blue", "green", "yellow"];

//A list of colour sequence generated by the program
let gamePattern = [];

//A list of colour sequence picked by the user
let userClickedPattern = [];

//Defining a variable to store the level value
let level = 0;

let isStarted = false;

//Generating a colour
function nextSequence() {
    //Displaying level number
    level+= 1;
    $("#level-title").text(`Level ${level}`);

    //Generating a random sequence of colours
    let randomNumber = Math.floor(Math.random() * 4);
    let randomChosenColour = buttonColours[randomNumber];
    gamePattern.push(randomChosenColour);

    //Creating a flashing animation
    $("#" + randomChosenColour).fadeOut(100).fadeIn(100);
    //Playing button sounds
    playSound(randomChosenColour);
    console.log(level);
}

//Adding an event listener on the buttons for user clicks 
$(".btn").on("click", function() {
    if(isStarted) {
        let userChosenColour = this.id;
        userClickedPattern.push(userChosenColour);
        playSound(userChosenColour);
        animatePress(userChosenColour);
    
        //Verifying the sequence picked by the user
        checkAnswer(userClickedPattern);  
    }
})

//Creating and playing the audio for button
function playSound(colour) {
    let buttonSound = new Audio(`sounds/${colour}.mp3`);
    buttonSound.play();
}

//Creating an animation when a button is clicked
function animatePress(currentColour) {
    let currentButton = $("#" + currentColour);
    currentButton.addClass("pressed");
    setTimeout(function() {
        currentButton.removeClass("pressed");
    }, 100)
}

//Starting the game on a keypress
$("*").on("keypress", function(e) {
    if(isStarted === false) {

        //Start the game
        isStarted = true;
        e.stopImmediatePropagation();
        nextSequence();
    }
});

//Validating user answer through cross checking with the game sequence
function checkAnswer(arr) {
    let index = arr.length - 1;
    if(arr[index] != gamePattern[index]) {
        console.log("wrong");
        //Playing game over audio
        let gameOverAudio = new Audio("sounds/wrong.mp3");
        gameOverAudio.play();

        //Background flashing red
        $("body").addClass("game-over");
        setTimeout(function() {
            $("body").removeClass("game-over")
        }, 200)

        //Displaying Game Over 
        $("#level-title").text("Game Over, Press Any Key to Restart");

        //Restart the game
        startOver();
        userClickedPattern = [];

    } else {
         //Level up on correct user sequence
         if(userClickedPattern.length === gamePattern.length) {
 
    
            //Setting up a delay of 1 sec before calling the next level
            setTimeout(function() {
                nextSequence()
            }, 1000)

            //Getting ready for next level
            userClickedPattern = [];
        }
    }
}

//Reset all values to default
function startOver() {
    isStarted = false;
    gamePattern = [];
    level = 0;
}





